[package]
name = "randy"
version = "1.7.0"
authors = ["Ian Page Hands <iphands@gmail.com>"]
edition = "2021"
description = "Conky like app in Rust"
homepage = "https://github.com/iphands/randy"
repository = "https://github.com/iphands/randy"
readme = "README.md"
license = "GPL-3.0"
exclude = ["/assets/*", "/scripts/*"]

[profile.dev]
opt-level = "s"
debug = 0

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = true
overflow-checks = false

[features]
runtime_bench = []
timings = []
packaged = []
nvidia = ["nvml-wrapper"]

[dependencies]
gtk = "0.18.2"
glib = "0.20.7"
serde = { version = "1.0.217", features = ["derive"] } # for toml
toml = "0.8.19"
serde_yml = "0.0.12"
clap = { version = "4.5.27", features = ["derive"] }
libc = "0.2.*"
# update process ...
gio = "0.9"
lazy_static = "1.4"
sensors = { version = "0.2", optional = true }
nvml-wrapper = { version = "0.6", optional = true }

[dev-dependencies]
rstest = "0.24.0"
