[package]
name = "ronky"
version = "0.1.0"
authors = ["Ian Page Hands <iphands@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.10.3"
gio = "0.9.1"
gtk = "0.9.2"
minimal-yaml = "0.1.2"
yaml-rust = "0.4.4"
libc = "0.2"
lazy_static = "1.4.0"