---
- text: SYSTEM
  items:
    - func: hostname
      text: "Hostname:"
    - func: kernel
      text: "Kernel:"
    - func: uptime
      text: "Uptime:"
    - func: ram_usage
      text: "RAM Usage:"
    - func: cpu_temp
      text: "CPU Temp:"
    - func: gpu_temp
      text: "GPU Temp:"
    - func: procs
      text: "Processes:"
    - func: load
      text: "Load:"
# - text: FILESYSTEM
#   items:
# - text: NETWORKING
#   items:
