---
settings:
  debug: false
  decoration: false
  resizable: false
  border: 10
  timeout: 1
ui:
  - text: SYSTEM
    items:
      - func: hostname
        text: "Hostname:"
      - func: kernel
        text: "Kernel:"
      - func: uptime
        text: "Uptime:"
      - func: cpu_usage
        text: "CPU Usage:"
        widget: bar
      - func: ram_usage
        text: "RAM Usage:"
        widget: bar
      - func: procs
        text: "Processes:"
      - func: load
        text: "Load:"
      - func: cpu_temp
        text: "CPU Temp:"
      - func: gpu_temp
        text: "GPU Temp:"

# - text: FILESYSTEM
#   items:
# - text: NETWORKING
#   items:
