---
settings:
  # color_bar:      "#e1eeff"
  # color_bar_med:  "#ffeeaa"
  # color_bar_high: "#ffaaaa"
  # color_background: "rgba(0, 0, 0, 0.5)"
  # color_label: "#87d7ff"
  # color_text:  "#e1eeeb"
  # decoration: false
  # font_family: "\"Liberation Mono\", monospace"
  # font_size: large
  # mod_top: 2
  # mod_fs: 5
  # resizable: false
  # skip_taskbar: true
  timeout: 1
  # xpos: 0
  # ypos: 0

ui:
  - text: SYSTEM
    type: system
    items:
      - func: hostname
        text: "Hostname:"

      - func: kernel
        text: "Kernel:"

      - func: uptime
        text: "Uptime:"

      - func: cpu_usage
        text: "CPU usage:"
        widget: bar

      - func: cpu_temp_sys
        text: "CPU temp:"

      - func: ram_usage
        text: "RAM usage:"
        widget: bar

      - func: procs_count
        text: "Running processes:"

      - func: load
        text: "Load:"

      # requires that you build with --features sensors
      # - func: sensor_info
      #   sensor_name: k10temp-pci-00c3
      #   label_name: Tdie
      #   val: "{}C"
      #   text: "CPU temp:"
      #   whole: true
      # - func: sensor_info
      #   sensor_name: k10temp-pci-00c3
      #   label_name: Vcore
      #   val: "{}mV"
      #   text: "CPU vcore:"
      #   whole: false

      # requires that you build with --features nvidia
      # - func: nvidia_gpu_temp
      #   text: "GPU Temp:"

  - text: CPUS
    type: cpus
    func: cpus
    text: "CPU"

  - text: TOP CPU
    type: cpu_consumers
    limit: 5

  - text: TOP MEMORY
    type: mem_consumers
    limit: 5

  - text: FILESYSTEM
    type: filesystem
    items:
      - text: "root:"
        mount_point: /
