---
settings:
  background_color: "#656565"
  debug: false
  decoration: false
  font-size: medium
  resizable: false
  timeout: 1
  xpos: 3050
  ypos: 10

ui:
  - text: SYSTEM
    items:
      - func: hostname
        text: "Hostname:"

      - func: kernel
        text: "Kernel:"

      - func: uptime
        text: "Uptime:"

      - func: cpu_usage
        text: "CPU Usage:"
        widget: bar

      - func: sensor_info
        sensor_name: k10temp-pci-00c3
        label_name: Tdie
        val: "{}C"
        text: "CPU Temp:"

      - func: sensor_info
        sensor_name: k10temp-pci-00c3
        label_name: Vcore
        val: "{}mV"
        text: "CPU Vcore:"

      - func: ram_usage
        text: "RAM Usage:"
        widget: bar

      - func: procs
        text: "Running Processes:"

      - func: load
        text: "Load:"


      # - func: cpu_temp_sys
      #   text: "CPU Temp:"

      # - func: gpu_temp
      #   text: "GPU Temp:"

  - text: CPUS
    items:
      - type: cpus
        func: cpus
        text: "CPU"

# - text: FILESYSTEM
#   items:
# - text: NETWORKING
#   items:
