---
settings:
  # color_bar:   "#e1eeeb"
  # color_label: "#d7d787"
  color_bar:   "#e1eeff"
  color_label: "#87d7ff"
  color_text:  "#e1eeeb"
  # decoration: false
  # resizable: false
  # skip_taskbar: true
  color_background: "#262626"
  font_size: large
  font_size_top: large
  timeout: 2
  xpos: 0
  ypos: 0

ui:
  - text: SYSTEM
    type: system
    items:
      - func: hostname
        text: "Hostname:"

      - func: kernel
        text: "Kernel:"

      - func: uptime
        text: "Uptime:"

      - func: cpu_usage
        text: "CPU usage:"
        widget: bar

      - func: cpu_temp_sys
        text: "CPU temp:"

      - func: ram_usage
        text: "RAM usage:"
        widget: bar

      - func: procs_count
        text: "Running processes:"

      - func: load
        text: "Load:"

  - text: CPUS
    type: cpus
    func: cpus
    text: "CPU"

  - text: TOP CPU
    type: cpu_consumers
    limit: 5

  - text: TOP MEMORY
    type: mem_consumers
    limit: 5

  - text: FILESYSTEM
    type: filesystem
    items:
      - text: "root:"
        mount_point: /
