[settings]
timeout = 1
color_bar = "#fff"
color_label = "#eee"
color_text = "#fff"
decoration = false
resizable = false
color_background = "#000"
font_size = "large"


[[ui]]
type = "cpu_consumers"

[[ui.item]]
func = "procs_count"
text = "Running processes:"

[[ui]]
type = "mem_consumers"
text = "TOP MEMORY"
limit = 5

[[ui.item]]
func = "load"
text = "Load:"
