---
settings:
  background_color: "#000"
  debug: false
  decoration: false
  font-size: x-large
  resizable: false
  timeout: 1

ui:
  - text: SYSTEM
    items:
      - func: hostname
        text: "Hostname:"

      - func: kernel
        text: "Kernel:"

      - func: uptime
        text: "Uptime:"

      - func: cpu_speed_rpi
        text: "CPU speed:"

      - func: cpu_temp_sys
        text: "CPU Temp:"

      - func: cpu_voltage_rpi
        text: "CPU voltage:"

      - func: cpu_usage
        text: "CPU usage:"
        widget: bar

      - func: ram_usage
        text: "RAM usage:"
        widget: bar

      - func: procs_count
        text: "Running processes:"

      - func: load
        text: "Load:"

  - text: CPUS
    type: cpus
    func: cpus
    text: "CPU"
